name: Factions_EnemyKillBonus
main: com.github.nerdshark.factions.EnemyKillBonusPlugin
version: 0.1
description: This plugin defines a multiplier that modifies the experience dropped when a player kills another player of an enemy faction.
author: nerdshark
depend: [Factions]